function cleanAccountProfile(p={}){return {remember:!!p?.remember,recall:!!p?.recall,suggestMemory:!!p?.suggestMemory,reading:{size:Math.min(26,Math.max(16,Number(p?.reading?.size)||18)),spacing:Math.min(2.2,Math.max(1.4,Number(p?.reading?.spacing)||1.8)),width:['narrow','comfortable','wide'].includes(p?.reading?.width)?p.reading.width:'comfortable'}}}
const personalKinds=new Set(['note','annotation','session','memory','position','setting','review']);
const str=(v,n=20000)=>typeof v==='string'?v.slice(0,n):'';
async function familyMember(request,env){
 const owner=request.headers.get('x-petey-user-id');if(!owner)return null;
 const row=await studyDB(env).prepare('SELECT * FROM members WHERE owner=?').bind(owner).first();
 return row?{...row,profile:JSON.parse(row.profile)}:null;
}
async function familyGate(request,env){const user=request.headers.get('x-petey-user-id');if(!user)return json({error:'Sign in to open your family study desk.',code:'SIGN_IN'},401);const m=await familyMember(request,env);return m?.active?null:json({error:m?'Your family access is paused. Ask the administrator to restore it.':'Enter your family invitation code to continue.',code:'FAMILY_ACCESS'},403)}
async function digestText(text){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),b=>b.toString(16).padStart(2,'0')).join('')}
// Thrown for problems with the client's request; the Worker entry turns it into a 4xx response instead of a server error.
class RequestError extends Error{constructor(message,status=400){super(message);this.status=status}}
async function requestData(request,max=200000){const raw=await request.text();if(raw.length>max)throw new RequestError('This item is too large.',413);let data;try{data=JSON.parse(raw)}catch{throw new RequestError('The request was not valid JSON.')}if(!data||typeof data!=='object'||Array.isArray(data))throw new RequestError('The request must be a JSON object.');return data}
async function familyAPI(request,env){
 const u=new URL(request.url),owner=request.headers.get('x-petey-user-id'),member=await familyMember(request,env),db=studyDB(env);
 if(u.pathname==='/api/account'&&request.method==='GET')return json({signedIn:!!owner,email:owner?request.headers.get('x-petey-user-email'):null,member:member?.active?{id:owner,name:member.name,role:member.role,profile:member.profile}:null,paused:!!member&&!member.active});
 if(!owner)return json({error:'Sign in first.'},401);
 if(request.method!=='GET'&&request.headers.get('Origin')!==u.origin)return json({error:'Invalid origin.'},403);
 if(u.pathname==='/api/account/redeem'&&request.method==='POST'){
  if(member)return member.active?json({joined:true}):json({error:'Ask the administrator to restore your access.'},403);
  const data=await requestData(request,4000),hash=await digestText(str(data.code,100).replace(/[\s-]/g,'').toUpperCase()),name=str(data.name,80).trim();if(!name)return json({error:'Enter the name you would like to use.'},400);
  const now=new Date().toISOString();await db.batch([
   db.prepare('UPDATE invitations SET redeemed_by=? WHERE hash=? AND redeemed_by IS NULL AND revoked=0 AND expires_at>?').bind(owner,hash,now),
   db.prepare("INSERT INTO members(owner,name,role,profile,joined_at) SELECT ?,?,'member','{}',? WHERE EXISTS (SELECT 1 FROM invitations WHERE hash=? AND redeemed_by=? AND revoked=0 AND expires_at>?) ON CONFLICT(owner) DO NOTHING").bind(owner,name,now,hash,owner,now)
  ]);const joined=await db.prepare('SELECT owner FROM members WHERE owner=?').bind(owner).first();return joined?json({joined:true}):json({error:'This invitation is invalid, expired, or already used.'},400);
 }
 if(!member?.active)return json({error:'Family access required.'},403);
 if(u.pathname==='/api/account'&&request.method==='PUT'){const d=await requestData(request,10000);const profile=cleanAccountProfile(d.profile);const name=str(d.name,80).trim()||member.name;await db.prepare('UPDATE members SET name=?,profile=? WHERE owner=?').bind(name,JSON.stringify(profile),owner).run();return json({member:{id:owner,name,role:member.role,profile}})}
 if(u.pathname==='/api/family/members'&&request.method==='GET'){const admin=member.role==='admin',rows=await db.prepare('SELECT m.owner,m.name,m.role,m.active,u.id AS login FROM members m LEFT JOIN users u ON u.id=m.owner WHERE m.active=1 OR ?=1').bind(admin?1:0).all();return json({members:rows.results.map(r=>({id:r.owner,name:r.name,role:r.role,active:!!r.active,...(admin?{hasLogin:!!r.login}:{})}))})}
 if(member.role!=='admin')return json({error:'Administrator access required.'},403);
 if(u.pathname==='/api/family/ai-status'&&request.method==='GET')return json({configured:!!env.OPENAI_API_KEY});
 if(u.pathname==='/api/family/ai-status'&&request.method==='POST'){if(!env.OPENAI_API_KEY)return json({error:'The OpenAI key is not configured.'},503);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-4.1',store:false,max_output_tokens:8,input:'Reply with the word Connected.'}),signal:AbortSignal.timeout(20000)});if(!r.ok)return json({error:r.status===429?'The OpenAI account has reached a usage or billing limit. Check its billing and usage settings, then test again.':r.status===401?'The configured API key was not accepted. Reconnect the key.':'OpenAI could not complete the connection check. Try again.'},r.status===429?429:502);const result=await r.json();const text=(result.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('');return text?json({ok:true,message:'The AI connection returned a response.',checkedAt:new Date().toISOString()}):json({error:'The connection returned no text. Try again.'},502)}catch{return json({error:'The AI connection timed out. Please retry.'},504)}}
 if(u.pathname==='/api/family/invitations'&&request.method==='GET'){const rows=await db.prepare('SELECT hash,label,expires_at,redeemed_by,revoked FROM invitations WHERE created_by=? ORDER BY expires_at DESC LIMIT 100').bind(owner).all();return json({invitations:rows.results})}
 if(u.pathname==='/api/family/invitations'&&request.method==='POST'){const d=await requestData(request,4000),code=Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase(),hash=await digestText(code),expires=new Date(Date.now()+7*86400000).toISOString();await db.prepare('INSERT INTO invitations(hash,label,created_by,expires_at) VALUES (?,?,?,?)').bind(hash,str(d.label,100)||'Family invitation',owner,expires).run();return json({code:code.match(/.{1,4}/g).join('-'),expiresAt:expires},201)}
 if(u.pathname==='/api/family/invitations'&&request.method==='DELETE'){const d=await requestData(request,4000);await db.prepare('UPDATE invitations SET revoked=1 WHERE hash=? AND created_by=?').bind(str(d.hash,64),owner).run();return json({revoked:true})}
 if(u.pathname==='/api/family/password-resets'&&request.method==='POST'){const d=await requestData(request,4000);return createPasswordReset(env,owner,d.id)}
 if(u.pathname==='/api/family/members'&&request.method==='PUT'){const d=await requestData(request,4000);if(d.id===owner)return json({error:'You cannot pause your own administrator access.'},400);await db.prepare("UPDATE members SET active=? WHERE owner=? AND role!='admin'").bind(d.active?1:0,str(d.id,200)).run();return json({saved:true})}
 return json({error:'Not found.'},404);
}
async function recordsAPI(request,env){
 const u=new URL(request.url),owner=request.headers.get('x-petey-user-id'),db=studyDB(env);
 if(request.method==='GET'){const rows=await db.prepare('SELECT kind,id,document,version,updated_at FROM personal_records WHERE owner=?').bind(owner).all();return json({records:rows.results.map(r=>({kind:r.kind,id:r.id,data:JSON.parse(r.document),version:r.version,updatedAt:r.updated_at}))})}
 if(request.method!=='PUT')return json({error:'Use GET or PUT.'},405);if(request.headers.get('Origin')!==u.origin)return json({error:'Invalid origin.'},403);
 const d=await requestData(request,500000);if(!personalKinds.has(d.kind)||!str(d.id,200)||d.id.length>200||!Number.isInteger(d.version)||d.version<0||!d.data||typeof d.data!=='object'||Array.isArray(d.data))return json({error:'Invalid personal item.'},400);
 d.data=cleanPersonalRecord(d.kind,d.data);const text=JSON.stringify(d.data);if(text.length>450000)return json({error:'This item is too large.'},413);const now=new Date().toISOString();
 const r=d.version===0?await db.prepare('INSERT INTO personal_records(owner,kind,id,document,version,updated_at) VALUES (?,?,?,?,1,?) ON CONFLICT(owner,kind,id) DO NOTHING').bind(owner,d.kind,d.id,text,now).run():await db.prepare('UPDATE personal_records SET document=?,version=version+1,updated_at=? WHERE owner=? AND kind=? AND id=? AND version=?').bind(text,now,owner,d.kind,d.id,d.version).run();
 return r.meta.changes?json({version:d.version+1,updatedAt:now}):json({error:'This item changed on another device. Your draft is kept here. Download it, then reload to merge your changes.',code:'CONFLICT'},409);
}
async function sharingAPI(request,env){const u=new URL(request.url),owner=request.headers.get('x-petey-user-id'),id=u.pathname.split('/')[3],db=studyDB(env);
 if(request.method==='GET'){const rows=await db.prepare('SELECT DISTINCT s.id,s.owner,s.document,s.created_at,m.name FROM shares s JOIN members m ON m.owner=s.owner LEFT JOIN share_recipients r ON r.share_id=s.id WHERE s.revoked=0 AND m.active=1 AND (s.owner=? OR r.recipient=?) ORDER BY s.created_at DESC').bind(owner,owner).all();const shares=rows.results.map(r=>({id:r.id,own:r.owner===owner,from:r.name,createdAt:r.created_at,...JSON.parse(r.document)}));return id?(shares.find(s=>s.id===id)?json({share:shares.find(s=>s.id===id)}):json({error:'This shared study is unavailable.'},404)):json({shares})}
 if(request.headers.get('Origin')!==u.origin)return json({error:'Invalid origin.'},403);
 if(request.method==='DELETE'&&id){await db.prepare('UPDATE shares SET revoked=1 WHERE id=? AND owner=?').bind(id,owner).run();return json({revoked:true})}
 if(request.method==='POST'){const d=await requestData(request),study=await ownedStudy(request,env,str(d.studyId,80));if(!study||study.deletedAt)return json({error:'Study not found.'},404);const ids=new Set(Array.isArray(d.entryIds)?d.entryIds:[]),entries=study.entries.filter(e=>ids.has(e.id)).map(e=>({...e,note:d.includeReflections?e.note:'',pinned:false}));if(!entries.length)return json({error:'Select at least one entry to share.'},400);const members=(await db.prepare('SELECT owner FROM members WHERE active=1 AND owner!=?').bind(owner).all()).results.map(x=>x.owner),recipients=[...new Set(Array.isArray(d.recipients)?d.recipients:[])].filter(x=>members.includes(x));if(!recipients.length)return json({error:'Choose a family member.'},400);const shareId=crypto.randomUUID(),document={title:str(d.title,160)||study.title,entries};await db.batch([db.prepare('INSERT INTO shares(id,owner,document,created_at) VALUES (?,?,?,?)').bind(shareId,owner,JSON.stringify(document),new Date().toISOString()),...recipients.map(recipient=>db.prepare('INSERT INTO share_recipients(share_id,recipient) VALUES (?,?)').bind(shareId,recipient))]);return json({id:shareId},201)}return json({error:'Use GET, POST, or DELETE.'},405)
}
async function consumeAIUse(request,env){const owner=request.headers.get('x-petey-user-id'),bucket='ai-'+new Date().toISOString().slice(0,10);const r=await studyDB(env).prepare('INSERT INTO usage(owner,bucket,count) VALUES (?,?,1) ON CONFLICT(owner,bucket) DO UPDATE SET count=count+1 WHERE count<100').bind(owner,bucket).run();return r.meta.changes?bucket:null}
// Gives back a counted question when the AI service returned no answer.
async function refundAIUse(request,env,bucket){if(!bucket)return;try{await studyDB(env).prepare('UPDATE usage SET count=count-1 WHERE owner=? AND bucket=? AND count>0').bind(request.headers.get('x-petey-user-id'),bucket).run()}catch{}}
