// Calendar content is fetched from dated official pages, never substituted with another date.
const calendarMemory=new Map();
const calEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function calTree(html){const root={tag:'root',attrs:{},children:[]},stack=[root];for(const token of html.match(/<!--[\s\S]*?-->|<![^>]*>|<[^>]+>|[^<]+/g)||[]){if(token.startsWith('<!'))continue;if(token.startsWith('</')){const tag=token.match(/^<\/([\w-]+)/)?.[1].toLowerCase();for(let i=stack.length-1;i>0;i--)if(stack[i].tag===tag){stack.length=i;break}continue}if(token.startsWith('<')){const tag=token.match(/^<([\w-]+)/)?.[1].toLowerCase();if(!tag)continue;const attrs={};for(const m of token.matchAll(/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))attrs[m[1].toLowerCase()]=m[2]??m[3];const n={tag,attrs,children:[]};stack.at(-1).children.push(n);if(!/^(img|br|hr|input|meta|link|source|wbr|area|embed|param|track|col)$/.test(tag)&&!token.endsWith('/>'))stack.push(n)}else stack.at(-1).children.push(token)}return root}
function calFind(n,test){if(typeof n==='string')return null;if(test(n))return n;for(const c of n.children){const found=calFind(c,test);if(found)return found}return null}
const calClass=(n,c)=>(n.attrs.class||'').split(/\s+/).includes(c);
function calText(n){return typeof n==='string'?n:n.children.map(calText).join('')}
function calDecode(s){return s.replace(/&(?:nbsp|amp|lt|gt|quot|apos|#39|#(\d+)|#x([a-f\d]+));/gi,(m,d,h)=>d||h?String.fromCodePoint(parseInt(d||h,h?16:10)):({'&nbsp;':' ','&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'",'&#39;':"'"}[m]||m)).replace(/\s+/g,' ').trim()}
function calURL(s){try{const u=new URL(calDecode(s),'https://wol.jw.org');return u.protocol==='https:'&&(u.hostname==='wol.jw.org'||u.hostname==='www.jw.org'||u.hostname.endsWith('.jw.org')||u.hostname.endsWith('.akamaihd.net'))?u.href:null}catch{return null}}
function calHTML(n,questions=[]){if(typeof n==='string')return (/^\s/.test(n)?' ':'')+calEscape(calDecode(n))+( /\s$/.test(n)?' ':'');if(['script','style','input','button','label','textarea'].includes(n.tag)||calClass(n,'pageNum')||calClass(n,'pswp'))return '';if(calClass(n,'gen-field')){const pid=n.attrs['data-pid'];if(!/^\d+$/.test(pid||''))return '';const id='q1-'+Number(pid).toString(16).padStart(16,'0');questions.push(id);return '<div data-official-question="'+id+'"></div>'}const body=n.children.map(c=>calHTML(c,questions)).join('');if(n.tag==='img'){const src=calURL(n.attrs.src);return src?`<img src="${calEscape(src)}" alt="${calEscape(calDecode(n.attrs.alt||''))}" loading="lazy" decoding="async">`:''}if(n.tag==='a'){const href=calURL(n.attrs.href);return href?`<a href="${calEscape(href)}" target="_blank" rel="noopener">${body}</a>`:body}if(!/^(div|section|header|h1|h2|h3|h4|p|em|strong|span|ul|ol|li|figure|figcaption|blockquote|br|hr|sup|sub)$/.test(n.tag))return body;let cls='';const c=n.attrs.class||'';if(/teal/.test(c))cls='wb-teal';else if(/maroon|red-600/.test(c))cls='wb-red';else if(/gold|yellow/.test(c))cls='wb-gold';if(calClass(n,'themeScrp'))cls+=' theme-scripture';const pid=n.attrs['data-pid'];return `<${n.tag}${cls?' class="'+cls.trim()+'"':''}${/^\d+$/.test(pid||'')?' id="official-p'+pid+'"':''}>${body}${['br','hr'].includes(n.tag)?'':'</'+n.tag+'>'}`}
async function calFetch(url){const r=await fetch(url,{headers:{Accept:'text/html'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Official source unavailable');const html=await r.text();if(html.length>2500000)throw Error('Source too large');return calTree(html)}
async function calCached(key,env,produce){const now=Date.now(),memory=calendarMemory.get(key);if(memory&&now-memory.fetchedAt<21600000)return memory;let stored;try{stored=await(await env.BUCKET?.get('calendar/v1/'+key+'.json'))?.json()}catch{}if(stored&&now-stored.fetchedAt<21600000){calendarMemory.set(key,stored);return stored}try{const result={...await produce(),fetchedAt:now};if(calendarMemory.size>40)calendarMemory.delete(calendarMemory.keys().next().value);calendarMemory.set(key,result);try{await env.BUCKET?.put('calendar/v1/'+key+'.json',JSON.stringify(result))}catch{}return result}catch(error){if(stored)return {...stored,cached:true};throw error}}
function calDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))throw Error('Invalid date');const d=new Date(value+'T12:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==value)throw Error('Invalid date');return d}
function calWeek(value){const date=calDate(value);date.setUTCDate(date.getUTCDate()-(date.getUTCDay()+6)%7);const start=date.toISOString().slice(0,10),thursday=new Date(date);thursday.setUTCDate(date.getUTCDate()+3);const year=thursday.getUTCFullYear(),jan4=new Date(Date.UTC(year,0,4,12));jan4.setUTCDate(jan4.getUTCDate()-(jan4.getUTCDay()+6)%7);return {start,year,week:1+Math.round((date-jan4)/604800000)}}
async function calendarWorkbookDocument(id,env){if(!/^\d{9}$/.test(id))throw Error('Invalid document');return calCached('workbook-'+id,env,async()=>{const url='https://wol.jw.org/en/wol/d/r1/lp-e/'+id,tree=await calFetch(url),article=calFind(tree,n=>n.attrs.id==='article'&&calClass(n,'pub-mwb'));if(!article)throw Error('Workbook not found');const header=calFind(article,n=>n.tag==='header'),body=calFind(article,n=>calClass(n,'bodyTxt'));if(!header||!body)throw Error('Workbook incomplete');const questions=[],html=calHTML(header,questions)+calHTML(body,questions);return {id:'wol-'+id,title:calDecode(calText(header)),html,questions,url}})}
async function legacyCalendarAPI(request,env){if(request.method!=='GET')return json({error:'Use GET.'},405);const u=new URL(request.url),date=u.searchParams.get('date');try{calDate(date)}catch{return json({error:'Choose a valid calendar date.'},400)}try{if(u.pathname==='/api/calendar/daily'){const data=await calCached('daily-'+date,env,async()=>{const [y,m,d]=date.split('-').map(Number),url=`https://wol.jw.org/en/wol/h/r1/lp-e/${y}/${m}/${d}`,tree=await calFetch(url),day=calFind(tree,n=>calClass(n,'tabContent')&&n.attrs['data-date']?.slice(0,10)===date);if(!day)throw Error('Requested daily text not found');const scripture=calFind(day,n=>calClass(n,'themeScrp')),body=calFind(day,n=>calClass(n,'bodyTxt'));if(!scripture||!body)throw Error('Daily text incomplete');return {date,url,scripture:calDecode(calText(scripture)),scriptureHTML:calHTML(scripture),html:calHTML(body)}});return json(data)}if(u.pathname==='/api/calendar/meeting'){const week=calWeek(date),data=await calCached('week-'+week.start,env,async()=>{const url=`https://wol.jw.org/en/wol/meetings/r1/lp-e/${week.year}/${week.week}`,tree=await calFetch(url),a=calFind(tree,n=>n.tag==='a'&&calClass(n,'pub-mwb')&&/^\/en\/wol\/d\/r1\/lp-e\/\d{9}$/.test(n.attrs.href||''));if(!a)throw Error('Current workbook not published');const doc=await calendarWorkbookDocument(a.attrs.href.split('/').at(-1),env);const expected=new Date(week.start+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',timeZone:'UTC'}).toUpperCase();if(!doc.title.toUpperCase().startsWith(expected))throw Error('Workbook date does not match requested week');const wt=calFind(tree,n=>n.tag==='a'&&calClass(n,'pub-w')&&/^\/en\/wol\/d\//.test(n.attrs.href||''));return {...doc,date:week.start,weekURL:url,watchtowerURL:wt?calURL(wt.attrs.href):null}});return json(data)}return json({error:'Not found.'},404)}catch{return json({error:'The official material for this date is unavailable right now. Please retry or open WOL.'},503)}}

async function calendarAPI(request,env){if(request.method!=='GET')return json({error:'Use GET.'},405);const u=new URL(request.url),date=u.searchParams.get('date');try{calDate(date)}catch{return json({error:'Choose a valid calendar date.'},400)}const kind=u.pathname.split('/').at(-1);if(!['daily','meeting','watchtower'].includes(kind))return json({error:'Not found.'},404);const key=kind==='daily'?date:calWeek(date).start;const material=(kind==='daily'?libraryCalendar.daily:kind==='watchtower'?libraryCalendar.watchtower:libraryCalendar.meetings)[key];if(!material)return json({error:kind==='daily'?'The daily-text publication for this date has not been added to your library yet.':kind==='watchtower'?'The assigned Watchtower article for this week is not in the uploaded library. Choose another week or browse your study editions.':'The workbook for this week has not been added to your library yet.'},404);if(kind==='watchtower'){const doc=await publication(material.id,env);return json({...material,pages:doc.pages.slice(material.page-1,material.endPage)})}return json({...material,...(kind==='meeting'?{watchtower:libraryCalendar.watchtower[key]||null}:{} )})}

async function referenceAPI(request){if(request.method!=='GET')return json({error:'Use GET.'},405);let url;try{url=new URL(new URL(request.url).searchParams.get('url'));if(url.protocol!=='https:'||!['wol.jw.org','www.jw.org','jw.org'].includes(url.hostname)||url.port||url.username||url.password)throw Error()}catch{return json({error:'Choose an official jw.org or WOL reference.'},400)}try{let response;for(let i=0;i<4;i++){response=await fetch(url.href,{redirect:'manual',headers:{Accept:'text/html'},signal:AbortSignal.timeout(15000)});if(response.status<300||response.status>=400)break;const next=new URL(response.headers.get('Location'),url);if(next.protocol!=='https:'||!['wol.jw.org','www.jw.org','jw.org'].includes(next.hostname)||next.port)throw Error();url=next}if(!response?.ok)throw Error();const html=await response.text();if(html.length>2500000)throw Error();const tree=calTree(html),article=calFind(tree,n=>n.attrs.id==='article'||n.tag==='article');if(!article)throw Error();const title=calFind(article,n=>n.tag==='h1'),body=calFind(article,n=>calClass(n,'bodyTxt'))||article;return json({title:title?calDecode(calText(title)):'Official reference',html:calHTML(body),text:calDecode(calText(calTree(calHTML(body)))),url:url.href})}catch{return json({error:'This official page could not be opened here. You can retry or open it directly.'},502)}}
