function needsOfficialCheck(text){return /\b(current|latest|recent|updated?|understanding|doctrin\w*|teach\w*|believ\w*|organizational|direction|governing body|disfellowship\w*|remov\w* from the congregation|blood transfusion|what does (?:the )?bible|what do (?:we|witnesses)|baptis\w*|trinity|fornication|sexual immorality|resurrection|prophec\w*|1914|607|144.?000)\b/i.test(text)||/\b(?:mean|interpret|explain|apply|principle)\b/i.test(text)&&/\b(?:scripture|verse|bible|matthew|john|romans|corinthians|revelation|genesis|psalm)\b/i.test(text)}
async function learningAPI(request,env){
 if(request.method!=='POST')return json({error:'Use POST.'},405);const origin=new URL(request.url).origin;if(request.headers.get('Origin')!==origin)return json({error:'Invalid origin.'},403);
 const input=await requestData(request,16000),study=await ownedStudy(request,env,str(input.studyId,80));if(!study||study.deletedAt||!study.guide)return json({error:'Guided study not found.'},404);
 if(study.version!==input.version)return json({error:'Your study changed. Save the latest answer, then try again.',code:'CONFLICT'},409);
 const step=study.guide.steps.find(s=>s.id===input.stepId);if(!step)return json({error:'Study step not found.'},404);
 if(!['clarify','another-source','explain','practice','continue'].includes(input.action))return json({error:'Choose a study action.'},400);
 if(!env.OPENAI_API_KEY)return json({error:'AI guidance is not connected. Your answer is saved; you can continue through the sources yourself.'},503);
 const {intent,results}=await rankedLibrary(study.guide.topic+' '+step.question,env),rows=await materializeSearch(results.filter(r=>r.kind==='passages').slice(0,24),origin,env,intent,6),sources=rows.map((r,i)=>({marker:'R'+i,title:r.title,url:r.url,text:r.text.slice(0,5000),publicationTitle:r.publicationTitle}));if(!sources.length)return json({error:'No supporting sources were found for this step.'},422);
 if(!await consumeAIUse(request,env))return json({error:'Today’s AI allowance is used. Your answers and sources remain available.'},429);
 const schema={type:'object',additionalProperties:false,required:['feedback','question','nextAction','sourceMarkers'],properties:{feedback:{type:'string'},question:{type:'string'},nextAction:{type:'string',enum:['clarify','another-source','explain','practice','continue']},sourceMarkers:{type:'array',items:{type:'string',enum:sources.map(s=>s.marker)}}}};
 try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+env.OPENAI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-4.1',store:false,max_output_tokens:1400,instructions:instructions+' Act as a patient study guide. Adapt to the learner’s own answer and requested action. Give a short source-backed clarification or a realistic practice question. Do not answer your follow-up question. For another-source, prefer a relevant source that is not in alreadyRead; be transparent if none is suitable. Identify a useful next action, without grading spirituality, guessing personal conduct, or making conscience decisions. Use only supplied source markers and summaries. This is study coaching, not current official direction. Preserve uncertainty and invite reading context. If an answer is blank, ask one approachable question rather than claiming to assess comprehension.',input:[{role:'user',content:JSON.stringify({goal:study.guide.goal,minutes:study.guide.minutes||15,step:{question:step.question,answer:step.answer,previous:step.coaching},action:input.action,alreadyRead:step.resources,sources})}],text:{format:{type:'json_schema',name:'adaptive_study_step',strict:true,schema}}}),signal:AbortSignal.timeout(90000)});
 if(!r.ok)return json({error:r.status===429?'The AI account has reached a usage or billing limit. Your answer is saved.':'AI coaching is unavailable. Your answer is saved; please retry.'},r.status===429?429:502);
 const body=await r.json();if(body.status==='incomplete')throw Error();const value=JSON.parse((body.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join(''));const resources=(value.sourceMarkers||[]).map(m=>sources.find(s=>s.marker===m));if(!value.feedback||!value.question||!resources.length||resources.some(x=>!x))throw Error();return json({version:study.version,coaching:{id:crypto.randomUUID(),feedback:str(value.feedback,4000),question:str(value.question,1500),nextAction:value.nextAction,resources:resources.map(({text,marker,...s})=>s),answer:'',createdAt:new Date().toISOString()}});
 }catch{return json({error:'The coaching response could not be checked reliably. Your answer is saved; please retry.'},502)}
}
