// Private learning context always comes from the authenticated owner's records.
const personalSource=s=>{let url='';try{const u=new URL(s?.url,'https://study.local');if(['https:','http:'].includes(u.protocol))url=str(s?.url,2000)}catch{}return {title:str(s?.title,500),url}};
function cleanPersonalRecord(kind,d){if(d.deletedAt)return {deletedAt:str(d.deletedAt,40)};if(kind==='memory')return {...d,text:str(d.text,3000),category:memoryCategories.includes(d.category)?d.category:'preference',source:personalSource(d.source),expiresAt:d.expiresAt&&Number.isFinite(+new Date(d.expiresAt))?new Date(d.expiresAt).toISOString():null,history:(Array.isArray(d.history)?d.history:[]).slice(-20).map(h=>({text:str(h.text,3000),date:str(h.date,40)}))};if(kind==='review')return {...d,prompt:str(d.prompt,2000),answer:str(d.answer,20000),draft:str(d.draft,20000),source:personalSource(d.source),dueAt:Number.isFinite(+new Date(d.dueAt))?new Date(d.dueAt).toISOString():new Date().toISOString(),history:(Array.isArray(d.history)?d.history:[]).slice(-100).map(h=>({text:str(h.text,20000),date:str(h.date,40)}))};return d}
const memoryCategories=['preference','goal','continuity','learning','temporary'];
const liveMemory=m=>!m.deletedAt&&m.text&&(!m.expiresAt||new Date(m.expiresAt)>new Date());
async function personalDocuments(owner,env){const [records,studies]=await Promise.all([studyDB(env).prepare('SELECT kind,id,document,updated_at FROM personal_records WHERE owner=?').bind(owner).all(),studyDB(env).prepare('SELECT id,document,updated_at FROM studies WHERE owner=?').bind(owner).all()]);return {records:records.results.map(r=>({...JSON.parse(r.document),kind:r.kind,id:r.id,updatedAt:r.updated_at})).filter(r=>!r.deletedAt),studies:studies.results.map(r=>({...JSON.parse(r.document),id:r.id,updatedAt:r.updated_at})).filter(r=>!r.deletedAt)}}
function personalItems(data,{forAI=false}={}){
 const items=[],add=(x)=>{if(x.text?.trim())items.push(x)};
 for(const d of data.studies){if(forAI&&d.excludeMemory)continue;const base='#notebook/'+d.id;
  add({type:'Study goal',title:d.title,text:d.question,url:base,date:d.updatedAt});
  add({type:'Personal reflection',title:d.title+' · takeaway',text:d.takeaway,url:base,date:d.updatedAt});
  for(const e of d.entries||[])add({type:({answer:'Previous AI response',scripture:'Saved scripture',passage:'Saved publication passage',question:'Open question',image:'Saved illustration'})[e.type]||'Personal reflection',title:d.title,text:e.text+(e.note?'\nMy reflection: '+e.note:''),url:base+'?entry='+e.id,date:e.createdAt,source:e.source,sources:e.sources,unresolved:e.type==='question'&&!e.resolved});
  for(const [i,s] of (d.guide?.steps||[]).entries())add({type:'Personal study answer',title:d.title+' · '+s.title,text:s.question+'\n'+s.answer,url:base+'?step='+i,date:d.updatedAt,sources:s.resources});
  for(const [i,m] of (d.chat||[]).entries())add({type:m.role==='assistant'?'Previous AI response':'Your question',title:d.title+' · conversation',text:m.content,url:base+'?message='+i,date:d.updatedAt,sources:(m.blocks||[]).flatMap(b=>b.annotations||[])});
 }
 for(const r of data.records){if(forAI&&r.excludeMemory)continue;
  if(r.kind==='session'){for(const [i,m] of (r.messages||[]).entries())add({type:m.role==='assistant'?'Previous AI response':'Your question',title:r.title||'Conversation',text:m.content,url:'#chat/'+r.id+'?message='+i,date:m.createdAt||r.updatedAt,sources:(m.blocks||[]).flatMap(b=>b.annotations||[])});}
  else if(r.kind==='review'){for(const h of r.history||[])add({type:'Your review reflection',title:r.prompt,text:h.text,url:'#review/'+r.id,date:h.date,source:r.source})}
  else if(['note','annotation','answer'].includes(r.kind))add({type:r.kind==='answer'?'Personal publication answer':r.kind==='annotation'?'Saved highlight':'Personal reflection',title:r.title||'Saved thought',text:[r.quote,r.text,r.note].filter(Boolean).join('\n'),url:r.kind==='answer'?r.url:'#saved/'+encodeURIComponent(r.id),date:r.updatedAt,source:{url:r.source||r.scope,title:r.title}});
 }return items;
}
async function privateRecall(owner,query,env,{forAI=false,limit=12}={}){
 const data=await personalDocuments(owner,env),intent=searchIntent(query),blocked=new Set(forAI?[...(data.records.find(r=>r.kind==='setting'&&r.id==='memory-forgotten-sources')?.urls||[]),...data.records.filter(r=>r.kind==='memory'&&!liveMemory(r)).map(r=>r.source?.url).filter(Boolean)]:[]),items=personalItems(data,{forAI}).filter(i=>!blocked.has(i.url));
 const model=await semanticIndex(),vector=semanticVector(intent,model);
 return items.map(item=>{const n=searchNormalize(item.title+' '+item.text),words=new Set(n.split(' '));let lexical=0;for(const [w,weight] of intent.weights)if(words.has(w))lexical+=weight;const v=semanticVector(searchIntent(item.title+' '+item.text.slice(0,6000)),model);const similarity=vector.reduce((sum,x,i)=>sum+x*v[i],0);const phrase=intent.normalized&&n.includes(intent.normalized)?5:0;return {...item,score:phrase+lexical*1.5+(similarity>.38?similarity*3:0)}}).filter(x=>x.score>1.5).sort((a,b)=>b.score-a.score).slice(0,limit).map(({score,...x})=>({...x,text:bestExcerpt(x.text,intent,1800)}));
}
function semanticVector(intent,model){const v=new Float32Array(model.dimensions);for(const [term,weight] of intent.weights){const i=model.vocab.get(term);if(i===undefined)continue;for(let j=0;j<v.length;j++)v[j]+=model.termVectors[i*v.length+j]*weight*model.idf[i]*model.scales[i]}const n=Math.hypot(...v);if(n)for(let j=0;j<v.length;j++)v[j]/=n;return v}
function canonicalSource(value){try{const u=new URL(value,'https://study.local');return decodeURIComponent(u.hash||u.href).replace(/\/$/,'')}catch{return ''}}
function samePassage(a,b){a=canonicalSource(a);b=canonicalSource(b);if(!a||!b)return false;if(a===b)return true;if(a.startsWith('#publication/')&&b.startsWith('#publication/'))return a.split('?')[0]===b.split('?')[0]&&(!a.includes('?anchor=')||!b.includes('?anchor='));const scripture=x=>x.match(/^#bible\/([^/]+)\/(\d+)(?:\/(\d+))?/),x=scripture(a),y=scripture(b);return !!(x&&y&&x[1]===y[1]&&x[2]===y[2]&&(!x[3]||!y[3]||x[3]===y[3]))}
async function personalAPI(request,env){
 const u=new URL(request.url),owner=request.headers.get('x-petey-user-id'),member=await familyMember(request,env),action=u.pathname.split('/')[3];
 if(request.method!=='GET')return json({error:'Use GET.'},405);
 if(action==='recall'){const query=str(u.searchParams.get('q'),1000);return json({items:query?await privateRecall(owner,query,env):[]})}
 const data=await personalDocuments(owner,env);
 if(action==='connections'){const source=str(u.searchParams.get('source'),2000),query=str(u.searchParams.get('q'),500);const used=personalItems(data).filter(item=>[item.source,...(item.sources||[])].some(s=>samePassage(s?.url,source)));const related=query?await privateRecall(owner,query,env,{limit:5}):[];return json({used:used.slice(0,40),related:related.filter(r=>!used.some(s=>s.url===r.url))})}
 if(action==='home'){
  const memory=data.records.filter(r=>r.kind==='memory'&&liveMemory(r)),dismissed=new Set(data.records.find(r=>r.kind==='setting'&&r.id==='home-dismissed')?.ids||[]),goals=memory.filter(r=>r.category==='goal'&&!dismissed.has('goal:'+r.id));let recommendation=null;
  if(member.profile.remember&&goals.length){const goal=goals[0],{intent,results}=await rankedLibrary(goal.text,env),rows=await materializeSearch(results.filter(r=>r.kind==='passages').slice(0,20),u.origin,env,intent,8);const chosen=rows.find(r=>!dismissed.has(r.url));if(chosen)recommendation={...chosen,goalId:goal.id,reason:'Because you chose this goal: '+goal.text}}
  const review=data.records.filter(r=>r.kind==='review'&&!r.paused&&r.dueAt<=new Date().toISOString()).sort((a,b)=>a.dueAt.localeCompare(b.dueAt))[0];const question=personalItems(data).find(i=>i.unresolved&&!dismissed.has(i.url));const recent=[...data.studies.filter(s=>!s.archived).map(s=>({title:s.title,url:'#notebook/'+s.id+(s.guide?'?step='+s.guide.step:''),detail:s.guide?'Step '+(s.guide.step+1)+' · '+s.guide.steps[s.guide.step]?.title:'Personal study',date:s.updatedAt})),...data.records.filter(r=>['position','session'].includes(r.kind)).map(r=>({title:r.title,url:r.kind==='session'?'#chat/'+r.id:r.url,detail:r.kind==='session'?'Conversation':'Reading',date:r.updatedAt}))].sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];return json({continue:recent,recommendation,revisit:review?{title:review.prompt,url:'#review/'+review.id,id:review.id}:question?{title:question.text,url:question.url}:null});
 }return json({error:'Not found.'},404);
}
