// Synonyms complement the corpus-trained latent model; they are retrieval hints, not doctrine.
const topicFamilies=[
 ['sex before marriage','premarital sex','fornication','sexual immorality','sexual relations'],
 ['anxiety','anxious','worry','worries','apprehension'],['depression','depressed','despondency','discouragement'],
 ['grief','bereavement','bereaved','mourning','loss of a loved one'],['loneliness','lonely','isolation'],
 ['anger','angry','rage','self control','mildness'],['forgiveness','forgive','forgiving','resentment'],
 ['peer pressure','bad association','companions','associations'],['bullying','bullies','harassment'],
 ['dating','courtship','choosing a mate','marriage mate'],['pornography','obscene','uncleanness'],
 ['work in the ministry','improving ministry','preaching','teaching','field service','disciple making'],
 ['return visits','follow up','cultivating interest'],['family worship','family study','family devotion'],
 ['raising children','parenting','parents','children','discipline'],['marital problems','marriage problems','husband','wife','communication'],
 ['money problems','financial stress','debt','finances','materialism'],['work stress','employment','secular work','balance'],
 ['prayer','pray','praying','supplication'],['faith','belief','conviction'],['trust in god','trust in jehovah','reliance','confidence'],
 ['bible reading','meditation','meditate','personal study'],['resurrection','raised from the dead','life after death'],
 ['death','dead','mortality'],['paradise','new world','everlasting life'],['kingdom of god','gods kingdom','government'],
 ['holy spirit','gods spirit','active force'],['jehovahs name','gods name','divine name'],
 ['humility','humble','modesty','modest'],['honesty','honest','truthfulness','lying'],['patience','patient','endurance','perseverance'],
 ['temptation','tempted','resist','self control'],['addiction','addictive','habits'],['alcohol','drinking','drunkenness'],
 ['persecution','opposition','trials','integrity'],['neutrality','politics','political'],['creation','creator','evolution'],
 ['baptism','baptized','dedication'],['conscience','conscientious','principles'],['repentance','repent','forgiveness'],
 ['suffering','suffer','evil','injustice'],['illness','sickness','health'],['old age','aging','elderly'],
 ['young people','youth','teenagers','adolescents'],['generosity','giving','hospitality'],['love','loving','affection'],
 ['peace','peaceable','peacemakers'],['joy','joyful','happiness'],['modest dress','clothing','appearance'],
 ['time management','priorities','schedule'],['social media','internet','online'],['entertainment','recreation','amusement'],
 ['gossip','slander','harmful speech'],['jealousy','envy','envious'],['divorce','separation'],['singleness','single','unmarried']
];
const searchNormalize=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim();
function searchIntent(query){const normalized=searchNormalize(query),families=topicFamilies.filter(f=>f.some(a=>{const n=searchNormalize(a);return (' '+normalized+' ').includes(' '+n+' ')}));const expanded=[...new Set(families.flat())].filter(a=>!normalized.includes(searchNormalize(a))).slice(0,18);const weights=new Map();for(const t of normalized.split(' ').filter(t=>t.length>=3&&!ignoredTerms.has(t)))weights.set(t,1);for(const phrase of expanded)for(const t of searchNormalize(phrase).split(' ').filter(t=>t.length>=3&&!ignoredTerms.has(t)))weights.set(t,Math.max(weights.get(t)||0,.8));if(!weights.size)for(const t of normalized.split(' ').filter(t=>t.length>=3))weights.set(t,1);return {normalized,expanded,weights};}
let semanticPromise,bibleLexPromise;
// Recently used search shards stay in memory (up to 8 of 26) instead of being fetched and unzipped from R2 on every search.
const shardCache=new Map();
async function searchShard(letter,env){let shard=shardCache.get(letter);if(shard)shardCache.delete(letter);else{shard=unpackObject('search/'+letter+'.json.gz',env);shard.catch(()=>shardCache.delete(letter))}shardCache.set(letter,shard);while(shardCache.size>8)shardCache.delete(shardCache.keys().next().value);return shard}
async function bibleLexicon(env){return bibleLexPromise??=(async()=>{const bible=await(biblePromise??=unpackObject('bible.json.gz',env)),index=new Map();for(const [book,chapters] of Object.entries(bible))for(const [chapter,verses] of Object.entries(chapters))for(const [v,value] of Object.entries(verses)){const id='b:'+book+':'+chapter+':'+v;for(const term of new Set(searchNormalize(value.text).split(' ').filter(t=>t.length>=3&&!ignoredTerms.has(t)))){if(!index.has(term))index.set(term,[]);index.get(term).push(id)}}return index})().catch(e=>{bibleLexPromise=null;throw e})}
function sourceTitle(meta,doc,page,intent){const section=[...(doc.contents||[])].reverse().find(c=>c.page<=page.number),bad=t=>!t||/REGULAR|degree|Boxes|Checks|X's|\?{2,}|How to Use This Booklet/i.test(t)||t.replace(/[^a-z]/gi,'').length<5;const footer=(page.blocks||[]).find(b=>/\? \d{1,4}$/.test(b.text||'')&&b.text.length<100);if(footer)return footer.text.replace(/ \d+$/,'');if(/^(?:it-|es)/.test(meta.id))return meta.title;const own=(page.blocks||[]).filter(b=>b.type==='h2'&&!bad(b.text));if(section&&!bad(section.title)&&page.number-section.page<16)return section.title.replace(/\s+/g,' ').trim();return own[0]?.text||meta.title;}

// The semantic index is inlined in the self-contained build, or read from R2 (semantic.json.gz) in the Cloudflare build.
async function semanticIndex(env){return semanticPromise??=(async()=>{const stream=packedSemantic?new Blob([Uint8Array.from(atob(packedSemantic),c=>c.charCodeAt(0))]).stream():(await env.BUCKET.get('semantic.json.gz'))?.body;if(!stream)throw Error('The search index is not available.');const m=await new Response(stream.pipeThrough(new DecompressionStream('gzip'))).json();const decode=s=>Int8Array.from(atob(s),c=>{const n=c.charCodeAt(0);return n>127?n-256:n});m.termVectors=decode(m.terms);m.docVectors=decode(m.documents);delete m.terms;delete m.documents;m.vocab=new Map(m.vocabulary.map((t,i)=>[t,i]));delete m.vocabulary;return m})().catch(e=>{semanticPromise=null;throw e})}
function publicationForKey(key){let lo=0,hi=publicationCatalog.length-1;while(lo<=hi){const m=(lo+hi)>>1,p=publicationCatalog[m];if(key<p.offset)hi=m-1;else if(key>=p.offset+p.pageCount)lo=m+1;else return p}return null}
function searchCategory(p){if(/^es(?:lp)?\d/.test(p.id))return 'daily';if(/^(?:it-|dx|scl_|wcgr_)/.test(p.id)||p.category==='indexes')return 'reference';if(/^(?:yb|syr)\d/.test(p.id))return 'history';if(p.category==='magazines')return /^w/.test(p.id)?'watchtower':/^g/.test(p.id)?'awake':'magazines';return p.category}
const searchCategoryNames={daily:'Daily texts',reference:'Reference works',history:'Yearbooks & reports',books:'Books',watchtower:'Watchtower',awake:'Awake!',brochures:'Brochures & booklets','meeting-workbook':'Meeting workbooks','kingdom-ministry':'Kingdom Ministry',guidelines:'Guidelines',indexes:'Indexes',magazines:'Other magazines',bible:'Bible'};
function bestExcerpt(text,intent,max=500){const pieces=String(text).replace(/\s+/g,' ').split(/(?<=[.!?])\s+(?=[A-Z“‘])/);let best=0,score=0;for(let i=0;i<pieces.length;i++){const t=searchNormalize(pieces[i]);let n=0;for(const [word,weight] of intent.weights)if((' '+t+' ').includes(' '+word+' '))n+=weight;for(const phrase of intent.expanded)if(t.includes(searchNormalize(phrase)))n+=2;if(n>score){score=n;best=i}}const joined=pieces.slice(Math.max(0,best-1),best+3).join(' ');if(joined.length<=max)return (best>1?'… ':'')+joined;const candidate=pieces.slice(best,best+2).join(' ');return (best>0?'… ':'')+candidate.slice(0,max).replace(/\s+\S*$/,'')+'…'}
async function rankedLibrary(query,env){
 const intent=searchIntent(query);if(/\d+:\d+/.test(query)){const direct=await retrieveScriptures(query,'https://study.local',env);for(const r of direct)for(const t of searchNormalize(r.text).split(' ').filter(t=>t.length>=3&&!ignoredTerms.has(t)))if(!intent.weights.has(t))intent.weights.set(t,.45)}const m=await semanticIndex(env),bibleTerms=await bibleLexicon(env),vector=new Float32Array(m.dimensions);let known=0;
 for(const [term,weight] of intent.weights){let i=m.vocab.get(term);if(i===undefined&&term.endsWith('s'))i=m.vocab.get(term.slice(0,-1));if(i===undefined)continue;known++;const w=weight*m.idf[i]*m.scales[i];for(let d=0;d<m.dimensions;d++)vector[d]+=m.termVectors[i*m.dimensions+d]*w;}
 const norm=Math.hypot(...vector);if(norm)for(let d=0;d<vector.length;d++)vector[d]/=norm;
 const terms=[...intent.weights.keys()].slice(0,45),lexical=new Map();let totalWeight=0;
 await Promise.all([...new Set(terms.map(t=>t[0]))].map(async letter=>{const shard=await searchShard(letter,env);for(const term of terms.filter(t=>t[0]===letter)){const postings=shard[term];if(!postings?.length)continue;const w=(intent.weights.get(term)||1)*Math.log(1+25000/postings.length);totalWeight+=w;for(const id of postings)lexical.set(id,(lexical.get(id)||0)+w)}}));
 for(const term of terms){const postings=bibleTerms.get(term);if(!postings)continue;const w=(intent.weights.get(term)||1)*Math.log(1+31000/postings.length);for(const id of postings)lexical.set(id,(lexical.get(id)||0)+w)}
 const results=[];
 for(let i=0;i<m.ids.length;i++){const id=m.ids[i],isBible=typeof id==='string';let semantic=0;if(known)for(let d=0;d<m.dimensions;d++)semantic+=vector[d]*m.docVectors[i*m.dimensions+d]/127;const lex=(lexical.get(id)||0)/(totalWeight||1);if(semantic<.34&&lex<.16)continue;const meta=isBible?null:publicationForKey(id);if(!isBible&&!meta)continue;const score=semantic*6+lex*8+(meta?.year>=2025?.7:0)-(meta?.largePrint?.15:0);if(score<2.15)continue;results.push({id,score:score*(meta?.category==='indexes'?.68:1),kind:isBible?'scriptures':'passages',meta,category:meta?searchCategory(meta):'bible'});}
 return {intent,results:addImportedSearch(results,intent,vector).sort((a,b)=>b.score-a.score)};
}
async function materializeSearch(rows,origin,env,intent,limit=20){const model=await semanticIndex(env),vector=semanticVector(intent,model),out=[],seen=new Set();for(const row of rows){if(out.length>=limit)break;if(row.kind==='scriptures'){const [_,book,chapter,verse]=row.id.split(':'),group=book+':'+chapter+':'+Math.floor((+verse-1)/3);if(seen.has(group))continue;const bible=await(biblePromise??=unpackObject('bible.json.gz',env)),text=bible[book]?.[chapter]?.[verse]?.text;if(!text)continue;seen.add(group);out.push({kind:'scriptures',category:'bible',id:row.id,title:book+' '+chapter+':'+verse,publicationTitle:'New World Translation',text:verse+' '+text,url:origin+'/#bible/'+encodeURIComponent(book)+'/'+chapter+'/'+verse,score:row.score});continue;}
 const meta=row.meta,number=row.id-meta.offset+1,doc=await publication(meta.id,env),page=doc?.pages[number-1];if(!page)continue;if(page.text.length<300)continue;const article=sourceTitle(meta,doc,page,intent),normalized=searchNormalize(page.text);const key=meta.title.replace(/large print/ig,'')+':'+normalized.slice(0,160);if(seen.has(key))continue;seen.add(key);const passage=closestPassage(page,intent,model,vector);out.push({kind:'passages',category:row.category,id:meta.id+':'+number,publicationId:meta.id,title:article,publicationTitle:meta.title,page:number,year:meta.year,largePrint:meta.largePrint,text:passage?.text||page.text,excerpt:bestExcerpt(passage?.text||page.text,intent),url:referenceURL(meta.id,number,origin,passage?.anchor),score:row.score});}return out;}
async function retrievePublications(query,origin,env,limit=6){const {intent,results}=await rankedLibrary(query,env);const rows=await materializeSearch(results.filter(r=>r.kind==='passages').slice(0,limit*3),origin,env,intent,limit);return rows.map((p,i)=>({...p,marker:'P'+(i+1)}))}
async function searchEverything(request,env){const u=new URL(request.url),query=(u.searchParams.get('q')||'').trim().slice(0,500),owner=request.headers.get('x-petey-user-id');if(request.method!=='GET')return json({error:'Use GET.'},405);if(!query)return json({results:[],groups:{},facets:{},total:0,related:[]});
 const kind=u.searchParams.get('type')||'all',category=u.searchParams.get('category')||'',pub=u.searchParams.get('publication')||'',year=u.searchParams.get('year')||'',offset=Math.max(0,Math.min(1000,Number(u.searchParams.get('offset'))||0)),limit=20;
 const [{intent,results},direct,studyRows,records]=await Promise.all([rankedLibrary(query,env),retrieveScriptures(query,u.origin,env),studyDB(env).prepare('SELECT id,document FROM studies WHERE owner=? ORDER BY updated_at DESC LIMIT 300').bind(owner).all(),studyDB(env).prepare("SELECT kind,id,document FROM personal_records WHERE owner=? AND kind IN ('note','annotation','session','answer') ORDER BY updated_at DESC LIMIT 3000").bind(owner).all()]);
 const privateMatch=text=>{if(!intent.normalized)return false;const n=searchNormalize(text);return n.includes(intent.normalized)||[...intent.weights.keys()].filter(t=>(' '+n+' ').includes(' '+t+' ')).length>=Math.min(2,intent.weights.size||100)};
 const privateRows=[];for(const row of studyRows.results){const d=JSON.parse(row.document);if(d.deletedAt)continue;const hay=[d.title,d.question,d.takeaway,...d.entries.map(e=>e.text+' '+e.note),...(d.guide?.steps||[]).map(s=>s.question+' '+s.answer)].join(' ');if(privateMatch(hay))privateRows.push({kind:'studies',title:d.title,text:bestExcerpt(hay,intent),url:'#notebook/'+row.id,score:8})}
 for(const row of records.results){if(!['note','annotation','session','answer'].includes(row.kind))continue;const d=JSON.parse(row.document);if(d.deletedAt)continue;const hay=[d.title,d.text,d.note,d.quote,...(d.messages||[]).map(m=>m.content)].filter(Boolean).join(' ');if(!privateMatch(hay))continue;privateRows.push({kind:'notes',title:d.title||'Saved thought',text:bestExcerpt(hay,intent),url:row.kind==='answer'?d.url:row.kind==='session'?'#chat/'+row.id:'#saved/'+encodeURIComponent(row.id),score:8})}
 const facets={types:{scriptures:0,passages:0,studies:0,notes:0},categories:{},years:{}};for(const r of results){facets.types[r.kind]++;if(r.meta){facets.categories[r.category]=(facets.categories[r.category]||0)+1;if(r.meta.year)facets.years[r.meta.year]=(facets.years[r.meta.year]||0)+1}}for(const r of privateRows)facets.types[r.kind]++;
 const matches=results.filter(r=>(kind==='all'||r.kind===kind)&&(!category||r.category===category)&&(!pub||r.meta?.id===pub)&&(!year||String(r.meta?.year)===year));
 // A bounded ranking window keeps broad queries and very large publications responsive.
 const pool=[...direct.map(d=>({...d,kind:'scriptures',category:'bible',score:50,direct:true})).filter(d=>(kind==='all'||kind==='scriptures')&&!category&&!year&&!pub),...privateRows.filter(d=>(kind==='all'||d.kind===kind)&&!category&&!year&&!pub),...matches.slice(0,500)].sort((a,b)=>b.score-a.score);
 const selected=pool.slice(offset,offset+limit),material=await materializeSearch(selected.filter(x=>!x.direct&&!['studies','notes'].includes(x.kind)),u.origin,env,intent,limit);let items=[...selected.filter(x=>x.direct||['studies','notes'].includes(x.kind)),...material].sort((a,b)=>b.score-a.score);items=items.filter((x,i,a)=>!a.slice(0,i).some(y=>y.url===x.url));const groups={scriptures:[],passages:[],studies:[],notes:[]};for(const item of items){const {score,...r}=item;groups[r.kind].push(r)}return json({results:items.map(({score,...r})=>r),groups,related:intent.expanded.slice(0,6),facets,categoryNames:searchCategoryNames,total:pool.length,nextOffset:offset+limit<pool.length?offset+limit:null,method:'local-hybrid'});
}
