import {sqliteTable,text,integer,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const studies=sqliteTable('studies',{
 owner:text('owner').notNull(),id:text('id').notNull(),document:text('document').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()
},t=>[primaryKey({columns:[t.owner,t.id]}),index('idx_studies_owner_updated').on(t.owner,t.updatedAt)]);
export const members=sqliteTable('members',{owner:text('owner').primaryKey(),name:text('name').notNull(),role:text('role').notNull().default('member'),active:integer('active').notNull().default(1),profile:text('profile').notNull().default('{}'),joinedAt:text('joined_at').notNull()});
export const invitations=sqliteTable('invitations',{hash:text('hash').primaryKey(),label:text('label').notNull(),createdBy:text('created_by').notNull(),expiresAt:text('expires_at').notNull(),redeemedBy:text('redeemed_by'),revoked:integer('revoked').notNull().default(0)});
export const personalRecords=sqliteTable('personal_records',{owner:text('owner').notNull(),kind:text('kind').notNull(),id:text('id').notNull(),document:text('document').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.owner,t.kind,t.id]}),index('idx_records_owner_kind').on(t.owner,t.kind)]);
export const shares=sqliteTable('shares',{id:text('id').primaryKey(),owner:text('owner').notNull(),document:text('document').notNull(),createdAt:text('created_at').notNull(),revoked:integer('revoked').notNull().default(0)},t=>[index('idx_shares_owner').on(t.owner)]);
export const shareRecipients=sqliteTable('share_recipients',{shareId:text('share_id').notNull(),recipient:text('recipient').notNull()},t=>[primaryKey({columns:[t.shareId,t.recipient]}),index('idx_shares_recipient').on(t.recipient)]);
export const usage=sqliteTable('usage',{owner:text('owner').notNull(),bucket:text('bucket').notNull(),count:integer('count').notNull().default(0)},t=>[primaryKey({columns:[t.owner,t.bucket]})]);
export const familySessions=sqliteTable('family_sessions',{id:text('id').primaryKey(),owner:text('owner').notNull(),document:text('document').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});
export const familyParticipants=sqliteTable('family_participants',{sessionId:text('session_id').notNull(),owner:text('owner').notNull()},t=>[primaryKey({columns:[t.sessionId,t.owner]}),index('idx_family_participant').on(t.owner)]);
export const familyContributions=sqliteTable('family_contributions',{sessionId:text('session_id').notNull(),id:text('id').notNull(),owner:text('owner').notNull(),document:text('document').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.sessionId,t.id]})]);
export const readingReports=sqliteTable('reading_reports',{id:text('id').primaryKey(),owner:text('owner').notNull(),document:text('document').notNull(),status:text('status').notNull().default('open'),updatedAt:text('updated_at').notNull()});
export const libraryState=sqliteTable('library_state',{id:text('id').primaryKey(),document:text('document').notNull(),updatedAt:text('updated_at').notNull()});
