import fs from 'node:fs';
import {buildCalendar} from './calendar-library.mjs';
const publicationCatalog=JSON.parse(fs.readFileSync('data/catalog.json','utf8'));
const calendarParserSource=fs.readFileSync('scripts/calendar-library.mjs','utf8').replace(/^import .*;\n/gm,'').replace(/^const load=.*;\n/m,'').replace("export function buildCalendar(){const catalog=JSON.parse(fs.readFileSync('data/catalog.json'));","return async function(catalog,documents){const load=id=>documents[id];").replace("crypto.createHash('sha256').update(text).digest('hex').slice(0,16)","(await digestText(text)).slice(0,16)");
const calendarParser='const calendarFromImportedDocuments=(()=>{'+calendarParserSource+'})();';
const refGroups=fs.readFileSync('public/scriptures.js','utf8').match(/const groups=(\[[^\n]+\]);/)[1];
const librarySource=fs.readFileSync('server/accounts.mjs','utf8')+'\nconst libraryCalendar='+JSON.stringify(buildCalendar())+';\n'+fs.readFileSync('server/studies.mjs','utf8')+'\nconst bibleReferenceGroups='+refGroups+';\nconst publicationCatalog='+JSON.stringify(publicationCatalog)+';\n'+fs.readFileSync('server/reader.mjs','utf8')+'\nconst packedSemantic='+JSON.stringify(fs.readFileSync('data/semantic.json.gz').toString('base64'))+';\n'+fs.readFileSync('server/search.mjs','utf8')+'\n'+fs.readFileSync('server/publications.mjs','utf8')+'\n'+fs.readFileSync('server/calendar.mjs','utf8')+'\n'+fs.readFileSync('server/personal.mjs','utf8')+'\n'+fs.readFileSync('server/learning.mjs','utf8')+'\n'+fs.readFileSync('server/family-sessions.mjs','utf8')+'\n'+calendarParser+'\n'+fs.readFileSync('server/reliability.mjs','utf8');
const types={html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'text/javascript; charset=utf-8',png:'image/png'};
const assets={};for(const name of fs.readdirSync('public')){const bytes=fs.readFileSync('public/'+name);assets['/'+name]={type:types[name.split('.').at(-1)]||'application/octet-stream',data:bytes.toString('base64')}}
const corpus=fs.readFileSync('server/sources/finn_persona_and_voice.md','utf8');
const retrieval=fs.readFileSync('server/source-test.mjs','utf8').replaceAll('export ','');
const source='const testSourceText='+JSON.stringify(corpus)+';\n'+retrieval+'\n'+fs.readFileSync('server/guided.mjs','utf8')+'\n'+fs.readFileSync('server/api.mjs','utf8').replace('export async function handleAPI','async function handleAPI');
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/server',{recursive:true});fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');fs.cpSync('drizzle','dist/drizzle',{recursive:true});
fs.writeFileSync('dist/server/index.js',librarySource+'\n'+source+'\nconst assets='+JSON.stringify(assets)+`;\nexport default { async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/account')||url.pathname.startsWith('/api/family/'))return await familyAPI(request,env);if(url.pathname.startsWith('/api/')&&url.pathname!=='/api/library-import'){const denied=await familyGate(request,env);if(denied)return denied;await ensureLibraryOverrides(env);}if(url.pathname.startsWith('/api/personal/'))return await personalAPI(request,env);if(url.pathname==='/api/learning')return await learningAPI(request,env);if(url.pathname.startsWith('/api/family-sessions'))return await familySessionAPI(request,env);if(url.pathname.startsWith('/api/reliability/'))return await reliabilityAPI(request,env);if(url.pathname==='/api/records')return await recordsAPI(request,env);if(url.pathname==='/api/reference')return await referenceAPI(request,env);if(url.pathname==='/api/search')return await searchEverything(request,env);if(url.pathname.startsWith('/api/shares'))return await sharingAPI(request,env);if(url.pathname.startsWith('/api/studies'))return await studiesAPI(request,env);if(url.pathname.startsWith('/api/calendar/'))return await calendarAPI(request,env);if(url.pathname==='/api/study-answers')return await studyAnswers(request,env);if(url.pathname.startsWith('/api/library-image/'))return libraryImage(request,env);if(url.pathname==='/api/library-import')return importLibrary(request,env);if(url.pathname.startsWith('/api/library-file/'))return libraryFile(request,env);if(url.pathname.startsWith('/api/publications')||url.pathname==='/api/bible')return await publicationAPI(request,env);if(url.pathname==='/api/test-source')return handleTestSource(request);if(url.pathname==='/api/guided-study')return await guidedAPI(request,env);if(url.pathname==='/api/chat')return await handleAPI(request,env);if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});const asset=assets[url.pathname==='/'?'/index.html':url.pathname];if(!asset)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0)),{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'}})}catch(error){console.error('Request failed',error.message);return Response.json({error:'The publication library is temporarily unavailable. Please try again.'},{status:503,headers:{'Cache-Control':'no-store'}})}}};`);
