import fs from 'node:fs';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
const months='JANUARY FEBRUARY MARCH APRIL MAY JUNE JULY AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER'.split(' ');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>s.replace(/\u030a/g,'¶').replace(/\u02b9/g,'').replace(/([A-Za-z])-\n([a-z])/g,'$1$2').replace(/\s+/g,' ').trim();
const load=id=>JSON.parse(zlib.gunzipSync(fs.readFileSync('data/publications/'+id+'.json.gz')));
export function buildCalendar(){const catalog=JSON.parse(fs.readFileSync('data/catalog.json'));const daily={},meetings={},watchtower={};
for(const p of catalog.filter(p=>/^es\d{2}_E$/.test(p.id))){const year=2000+Number(p.id.slice(2,4)),doc=load(p.id);let all='',positions=[];for(const page of doc.pages){positions.push({start:all.length,page:page.number});all+=page.text+'\n'}const re=new RegExp('^(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\\s+('+months.map(s=>s[0]+s.slice(1).toLowerCase()).join('|')+')\\s+(\\d{1,2})\\s*$','gm');const matches=[...all.matchAll(re)];for(let i=0;i<matches.length;i++){const m=matches[i],date=`${year}-${String(months.indexOf(m[1].toUpperCase())+1).padStart(2,'0')}-${m[2].padStart(2,'0')}`,text=clean(all.slice(m.index+m[0].length,matches[i+1]?.index??all.length));let split=text.match(/^([\s\S]*?—[^\d]{0,3}(?:[1-3] )?[A-Za-z. ]{1,35}\d[\d:,;\s–-]*(?:ftn)?\.)\s+([\s\S]*)$/);if(!split){if(year>=2025)throw Error('Daily scripture boundary: '+date);split=[text,'',text];}const page=positions.filter(x=>x.start<=m.index).at(-1).page;daily[date]={date,scripture:split[1],scriptureHTML:'<p class="theme-scripture">'+esc(split[1])+'</p>',html:'<p>'+esc(split[2])+'</p>',url:`#publication/${p.id}/${page}`,publicationId:p.id,page,source:'Uploaded publication'};}}
for(const p of catalog.filter(p=>/^mwb_E_\d{6}$/.test(p.id))){const year=+p.id.slice(-6,-2),doc=load(p.id);const starts=[];for(const pg of doc.pages){const re=new RegExp('('+months.join('|')+')\\s+(\\d{1,2})\\s*[-–]\\s*(?:('+months.join('|')+')\\s+)?(\\d{1,2})\\s*ʹ\\s*([^\\n]+)');const m=pg.text.match(re);if(m){const date=`${year}-${String(months.indexOf(m[1])+1).padStart(2,'0')}-${m[2].padStart(2,'0')}`;starts.push({date,m,page:pg.number})}}
for(let w=0;w<starts.length;w++){const start=starts[w],end=doc.pages.find(pg=>pg.number>=start.page&&/Concluding Comments/.test(pg.text))?.number||((starts[w+1]?.page||doc.pages.length+1)-1),pages=doc.pages.slice(start.page-1,end);let raw=pages.map(x=>x.text).join('\n');const title=clean(start.m[0].split('ʹ')[0]),reading=clean(start.m[5]);const opening=raw.match(/Song\s+\d+\s+and Prayer[\sʹ]*Opening Comments\s*\(1 min\.\)/)?.[0]||'';raw=raw.replace(start.m[0],'').replace(opening,'').replace(/Christian Congregation of Jehovah’s Witnesses\.[\s\S]*?Printed in Canada\./g,'').replace(/\b(?:TREASURES\s+FROM GOD’S WORD|APPLY YOURSELF\s+TO THE FIELD MINISTRY)\b/g,'').replace(/^\s*\d{1,2}\s*$/gm,'').replace(/^\s*[ʹ̆]\s*\d{4}\s*$/gm,'');const livingAt=raw.search(/LIVING\s+AS CHRISTIANS/);let images=pages.flatMap(pg=>(pg.blocks||[]).filter(b=>b.type==='image').map(b=>({...b,page:pg.number})));for(const image of images){if(image.caption&&!/APPLY YOURSELF|TREASURES|LIVING AS/.test(image.caption)){const norm=clean(image.caption);const pattern=norm.split(' ').map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('\\s+');raw=raw.replace(new RegExp(pattern),'')}}const hits=[...raw.matchAll(/(?:^|\n)(\d{1,2})\.\s+([^\n]+)/g)].filter(m=>+m[1]<=12);const blocks=[],questions=[];const imageHTML=b=>`<figure><img src="/api/library-image/${p.id}/${b.imageId}.webp?v=${b.digest}" alt="${esc(b.alt||'Workbook illustration')}" loading="lazy">${b.caption&&!/APPLY YOURSELF|TREASURES|LIVING AS/.test(b.caption)?'<figcaption>'+esc(b.caption)+'</figcaption>':''}</figure>`;
let html=`<header><h1>${esc(title)}</h1><h2>${esc(reading)}</h2></header><p class="workbook-opening">${esc(clean(opening))}</p>`;
const existing=pages.flatMap(pg=>(pg.blocks||[]).filter(b=>b.type==='question'));
for(let i=0;i<hits.length;i++){const hit=hits[i],num=+hit[1],chunk=raw.slice(hit.index, hits[i+1]?.index??raw.length).trim();const head=chunk.match(/^\d+\.\s*([\s\S]*?\(\d+ min\.\))/);if(!head)throw Error('Assignment heading '+p.id+' '+start.date+' '+num);let body=chunk.slice(head[0].length).replace(/LIVING\s+AS CHRISTIANS/g,'');let closing='';const closingAt=body.indexOf('Concluding Comments');if(closingAt>=0){closing=clean(body.slice(closingAt));body=body.slice(0,closingAt)}let song='';body=body.replace(/\s*Song\s+(\d+)\s*$/,(m,n)=>{song='Song '+n;return ''});if(num===1)html+='<h2 class="workbook-section wb-teal">TREASURES FROM GOD’S WORD</h2>';if(num===4)html+='<h2 class="workbook-section wb-gold">APPLY YOURSELF TO THE FIELD MINISTRY</h2>';if((livingAt>=0&&hit.index>livingAt)&&!html.includes('class="workbook-section wb-red"'))html+='<h2 class="workbook-section wb-red">LIVING AS CHRISTIANS</h2>';
html+='<section class="workbook-part"><h3>'+esc(clean(head[0]))+'</h3>';
const paras=body.replace(/\n\s*̇\s*/g,'\n\n').replace(/\n(?=What spiritual gems|What Bible truth|A householder|Read\s|Play the VIDEO)/g,'\n\n').split(/\n\s*\n/).map(clean).filter(Boolean);for(const text of paras){const page=pages.find(pg=>clean(pg.text).includes(text.slice(0,60)))?.number||start.page;if(text.includes('?')){const old=existing.find(b=>clean(b.text)===text);const qid=old?.questionId||'q'+page+'-'+crypto.createHash('sha256').update(text).digest('hex').slice(0,16);questions.push(qid);blocks.push({type:'question',text,questionId:qid});html+='<p>'+esc(text)+'</p><div data-official-question="'+qid+'"></div>'}else html+='<p>'+esc(text)+'</p>'}
if(num===1){const picture=images.find(b=>b.page===start.page);if(picture){html+=imageHTML(picture);images=images.filter(b=>b!==picture)}}if(num>=7&&images.length){html+=images.map(imageHTML).join('');images=[]}html+='</section>';if(song)html+='<p class="workbook-song">'+esc(song)+'</p>';if(closing)html+='<p class="workbook-closing">'+esc(closing)+'</p>'}
if(images.length)html+=images.map(imageHTML).join('');if(!hits.length)throw Error('No assignments: '+start.date);meetings[start.date]={id:p.id,date:start.date,title:title+' · '+reading,html,questions,blocks,url:`#publication/${p.id}/${start.page}`,weekURL:`#publication/${p.id}/${start.page}`,source:'Uploaded publication',page:start.page};}}
const memorialId='mwb_E_202603';if(catalog.some(p=>p.id===memorialId)){const doc=load(memorialId),pages=doc.pages.filter(p=>[8,9].includes(p.number));if(pages[0]?.text.includes('2026 Memorial'))meetings['2026-03-30']={id:memorialId,date:'2026-03-30',title:'Memorial Bible Reading Schedule',html:'<header><h1>March 30–April 5</h1><h2>Memorial Bible Reading Schedule</h2></header><p>This issue provides the Memorial Bible reading schedule for these dates.</p>'+pages.map(p=>'<section data-source-page="'+p.number+'"><p>'+esc(p.text).replace(/\n/g,'<br>')+'</p></section>').join(''),questions:[],blocks:[],url:'#publication/'+memorialId+'/8',weekURL:'#publication/'+memorialId+'/8',source:'Uploaded publication',page:8};}
for(const p of catalog.filter(p=>/^w_E_\d{6}$/.test(p.id))){const doc=load(p.id);for(const pg of doc.pages){const re=new RegExp('(?:^|\\n)('+months.join('|')+')\\s+(\\d{1,2})\\s*[-–]\\s*(?:('+months.join('|')+')\\s+)?(\\d{1,2}),?\\s+(20\\d{2})(?:\\n|$)');const m=pg.text.match(re);if(!m)continue;const date=`${m[5]}-${String(months.indexOf(m[1])+1).padStart(2,'0')}-${m[2].padStart(2,'0')}`;const heading=doc.contents?.find(c=>c.page===pg.number);if(!heading)continue;const next=doc.contents.find(c=>c.page>pg.number);watchtower[date]={id:p.id,date,title:heading.title,page:pg.number,endPage:(next?.page||doc.pages.length+1)-1,url:`#publication/${p.id}/${pg.number}`,source:'Uploaded publication',year:p.year};}}
return {daily,meetings,watchtower};}
