import fs from 'node:fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {Readable} from 'node:stream';import {createHash} from 'node:crypto';
import {buildCalendar} from './calendar-library.mjs';
import {default as worker} from '../dist/server/index.js';
export function testEnvironment(){
 const db=new DatabaseSync(':memory:');liveDatabases.add(db);
 for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql'))) db.exec(fs.readFileSync('drizzle/'+file,'utf8'));
 for(const owner of ['person-a','person-b','person-c'])db.prepare("INSERT INTO members(owner,name,role,profile,joined_at) VALUES (?,?,?,?,?)").run(owner,owner,owner==='person-a'?'admin':'member','{}',new Date().toISOString());
 const objects=new Map();
 let batchQueue=Promise.resolve();const DB={batch(statements){const run=async()=>{db.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}};const result=batchQueue.then(run);batchQueue=result.catch(()=>{});return result},prepare(sql){return {bind(...args){const stmt=db.prepare(sql);return {
 first:async()=>stmt.get(...args)||null,
 all:async()=>({results:stmt.all(...args)}),
 run:async()=>({meta:{changes:Number(stmt.run(...args).changes)}})
 }}}}};
 const bytes=async value=>typeof value==='string'?Buffer.from(value):value instanceof ArrayBuffer?Buffer.from(value):ArrayBuffer.isView(value)?Buffer.from(value):value?.getReader?Buffer.from(await new Response(value).arrayBuffer()):Buffer.from(String(value));
 const object=(value,range)=>{let b=Buffer.from(value);const size=b.length;if(range?.offset!==undefined)b=b.subarray(range.offset,range.offset+range.length);return {size,body:Readable.toWeb(Readable.from([b])),json:async()=>JSON.parse(b.toString()),text:async()=>b.toString(),arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}};
 const BUCKET={async get(key,options){if(objects.has(key))return object(objects.get(key),options?.range);if(fs.existsSync('data/'+key))return object(fs.readFileSync('data/'+key),options?.range);return null},async put(key,value){objects.set(key,await bytes(value))},async head(key){const o=await this.get(key);return o?{size:o.size}:null},async delete(key){objects.delete(key)},async list({prefix='',limit=1000,cursor}={}){const keys=[...objects.keys()].filter(k=>k.startsWith(prefix)).sort(),offset=Number(cursor)||0,selected=keys.slice(offset,offset+limit);return {objects:selected.map(key=>({key,size:objects.get(key).length})),truncated:offset+limit<keys.length,cursor:String(offset+limit)}}};
 return {DB,BUCKET,OPENAI_API_KEY:'test-only',testDB:db};
}
// Test sign-in: each owner gets a user row and a session in every live test database, and requests carry its session cookie.
const liveDatabases=new Set();
export function sessionCookie(owner){const token=createHash('sha256').update('test-session:'+owner).digest('hex'),hash=createHash('sha256').update(token).digest('hex'),now=new Date().toISOString();for(const db of liveDatabases){db.prepare('INSERT OR IGNORE INTO users(id,email,password_hash,created_at) VALUES (?,?,?,?)').run(owner,owner+'@family.test','test-only',now);db.prepare('INSERT OR IGNORE INTO auth_sessions(token_hash,user_id,created_at,expires_at) VALUES (?,?,?,?)').run(hash,owner,now,'2999-01-01T00:00:00.000Z')}return '__Host-petey_session='+token}
export const request=(path,{owner='person-a',method='GET',body,origin='https://study.test'}={})=>new Request('https://study.test'+path,{method,headers:{...(owner?{Cookie:sessionCookie(owner)}:{}),Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
if(import.meta.url===new URL(process.argv[1],'file:').href){const env=testEnvironment();const c=buildCalendar();assert.equal(Object.keys(c.daily).filter(x=>x.startsWith('2026')).length,365);assert.equal(Object.keys(c.meetings).filter(x=>x.startsWith('2026')).length,52);let external=0;const realFetch=globalThis.fetch;globalThis.fetch=async()=>{external++;throw Error('Network disabled')};
for(const date of ['2026-01-01','2026-09-24','2026-12-31']){const r=await worker.fetch(request('/api/calendar/daily?date='+date),env);assert.equal(r.status,200);assert.equal((await r.json()).date,date)}for(const date of ['2026-09-24','2026-09-28','2026-11-02','2027-01-01'])assert.equal((await worker.fetch(request('/api/calendar/meeting?date='+date),env)).status,200);assert.equal(external,0);assert.match(c.daily['2026-09-24'].scripture,/Exult/);assert.match(c.meetings['2026-09-21'].html,/library-image\/mwb_E_202609/);assert.equal((await worker.fetch(request('/api/calendar/daily?date=2027-01-01'),env)).status,404);
const path='/api/studies/test-study-001',body={title:'My study',entries:[{id:'entry-0001',type:'note',text:'A private thought'}],chat:[]};let r=await worker.fetch(request(path,{method:'POST',body}),env);assert.equal(r.status,201);let s=(await r.json()).study;assert.equal(s.version,1);assert.equal((await worker.fetch(request(path,{owner:'person-b'}),env)).status,404);assert.equal((await worker.fetch(request(path,{owner:null}),env)).status,401);assert.equal((await worker.fetch(request(path,{method:'PUT',body:s,origin:'https://evil.test'}),env)).status,403);s.title='Changed';r=await worker.fetch(request(path,{method:'PUT',body:s}),env);assert.equal(r.status,200);assert.equal((await worker.fetch(request(path,{method:'PUT',body:s}),env)).status,409);s=(await r.json()).study;s.deletedAt=new Date().toISOString();r=await worker.fetch(request(path,{method:'PUT',body:s}),env);assert.equal(r.status,200);s=(await r.json()).study;s.deletedAt=null;r=await worker.fetch(request(path,{method:'PUT',body:s}),env);assert.equal(r.status,200);s=(await r.json()).study;assert.equal(s.entries[0].text,'A private thought');const other=await(await worker.fetch(request('/api/studies',{owner:'person-b'}),env)).json();assert.equal(other.studies.length,0);
const meeting=c.meetings['2026-09-21'];r=await worker.fetch(request('/api/study-answers?publication='+meeting.id,{method:'PUT',body:{questionId:meeting.questions[0],text:'My answer'}}),env);assert.equal(r.status,200);
let payload;globalThis.fetch=async(url,opts)=>{payload=JSON.parse(opts.body);return Response.json({output:[{type:'message',content:[{type:'output_text',text:'A test-only study response [S1].'}]}]})};r=await worker.fetch(request('/api/chat',{method:'POST',body:{studyId:s.id,studyScope:'study',messages:[{role:'user',content:'What is in this study?'}]}}),env);assert.equal(r.status,200);const answer=await r.json();assert.equal(answer.blocks[0].annotations.length,1);assert.match(payload.input[0].content,/A private thought/);assert.match(payload.instructions,/not authoritative publications/);assert.equal((await worker.fetch(request('/api/chat',{owner:'person-b',method:'POST',body:{studyId:s.id,messages:[{role:'user',content:'Show me'}]}}),env)).status,404);globalThis.fetch=realFetch;console.log('Passed: 365 daily texts + 52 workbook weeks without network; source images; new answer fields; private study CRUD; cross-account isolation; stale-write protection; Trash restore; study-only AI context and citations.');}
