import fs from 'node:fs';
import {JSDOM,VirtualConsole} from 'jsdom';
import worker from '../dist/server/index.js';
import {testEnvironment,request} from './check-studies.mjs';
export async function openUI({env=testEnvironment(),owner='person-a',hash='home',local={}}={}){
 const errors=[],html=(await(await worker.fetch(request('/'),env)).text()).replace(/<script src="boot.js"><\/script>/,''),vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/Could not parse CSS|navigation to another Document/.test(e.message))errors.push(e.stack||e.message)});
 const dom=new JSDOM(html,{url:'https://study.test/#'+hash,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.fetch=async(path,opts={})=>{if(opts.signal?.aborted)throw new w.DOMException('Aborted','AbortError');const r=await worker.fetch(request(path,{owner,method:opts.method||'GET',body:opts.body?JSON.parse(opts.body):undefined}),env);if(opts.signal?.aborted)throw new w.DOMException('Aborted','AbortError');return r};w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};const D=w.Date;w.Date=class extends D{constructor(...args){super(...(args.length?args:['2026-09-24T12:00:00Z']))}static now(){return +new D('2026-09-24T12:00:00Z')}};}});
 const w=dom.window,d=w.document;w.structuredClone=structuredClone;w.CSS={escape:s=>String(s)};for(const [k,v] of Object.entries(local))w.localStorage.setItem(k,JSON.stringify(v));const append=w.Node.prototype.appendChild;w.Node.prototype.appendChild=function(node){if(node.tagName==='SCRIPT'&&node.src){try{const script=d.createElement('script');script.textContent=fs.readFileSync('public/'+node.src.split('/').at(-1),'utf8');append.call(d.body,script);queueMicrotask(()=>node.onload?.())}catch(e){errors.push(e.stack);queueMicrotask(()=>node.onerror?.(e))}return node}return append.call(this,node)};const appendMany=w.Element.prototype.append;w.Element.prototype.append=function(...nodes){for(const n of nodes){if(n?.tagName==='SCRIPT'&&n.src)w.Node.prototype.appendChild.call(this,n);else appendMany.call(this,n)}};w.eval(fs.readFileSync('public/boot.js','utf8'));
 const wait=async(fn,message)=>{for(let i=0;i<500;i++){if(fn())return;await new Promise(r=>setTimeout(r,10))}throw Error((message||'Timed out')+' '+errors.join(' | '))};
 const input=(el,value,event='input')=>{if(!el)throw Error('Missing input');el.value=value;el.dispatchEvent(new w.Event(event,{bubbles:true}))},submit=f=>f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 return {w,d,env,errors,wait,input,submit,close:()=>w.close()};
}
